
import com.mycompany.bookingsystem.Musical;
import com.mycompany.bookingsystem.Ticket;
import com.mycompany.bookingsystem.TicketingSystem;
import java.util.*;
import java.io.*;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        musicalListButton = new javax.swing.JButton();
        showSchedulesButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        musicalName = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        adultTicketType = new javax.swing.JRadioButton();
        studentTicketType = new javax.swing.JRadioButton();
        seniorTicketType = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dayOfMusicals = new javax.swing.JComboBox<>();
        timeSlot = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        seatNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        numberOfTickets = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        musicalTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musical Ticketing");
        setBackground(new java.awt.Color(204, 204, 255));
        setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MUSICALS");

        musicalListButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        musicalListButton.setText("Musical List");
        musicalListButton.setName("musicalListButton"); // NOI18N
        musicalListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicalListButtonActionPerformed(evt);
            }
        });

        showSchedulesButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        showSchedulesButton.setText("Show Schedules");
        showSchedulesButton.setToolTipText("show available dates, time slots, and seats of musicals.");
        showSchedulesButton.setName("showSchedulesButton"); // NOI18N
        showSchedulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSchedulesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showSchedulesButton)
                            .addComponent(musicalListButton))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicalListButton)
                .addGap(40, 40, 40)
                .addComponent(showSchedulesButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOOK TICKET");

        musicalName.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        musicalName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamma Mia", "The Lion King", "Frozen", "Wicked\t", "Matilda" }));
        musicalName.setName("musicalsComboBox"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ticket Type");

        adultTicketType.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        adultTicketType.setText("Adult ($16)");
        adultTicketType.setName("adultTicketRadioButton"); // NOI18N
        adultTicketType.setOpaque(true);

        studentTicketType.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        studentTicketType.setText("Senior ($10)");
        studentTicketType.setName("seniorTicketRadioButton"); // NOI18N

        seniorTicketType.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        seniorTicketType.setText("Student ($7)");
        seniorTicketType.setName("studentTicketRadioButton"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Musical");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Other");

        dayOfMusicals.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sun", "Mon", "Tue", "Wed", "Thur", "Fri", "Sat" }));
        dayOfMusicals.setName("dayComboBox"); // NOI18N

        timeSlot.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        timeSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11:00 AM", "04:00 PM", "07:00 PM" }));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seat no.");

        seatNumber.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        seatNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seatNumber.setText("0");
        seatNumber.setName("seatNumberTextEntry"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Day:");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Time slot:");

        bookButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        bookButton.setText("Book");
        bookButton.setName("bookButton"); // NOI18N
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        printButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        printButton.setText("Print ");
        printButton.setToolTipText("Print a reciept of your order");
        printButton.setName("printButton"); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel9.setText("no. of tickets");
        jLabel9.setName(""); // NOI18N

        numberOfTickets.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        numberOfTickets.setText("1");
        numberOfTickets.setName("noOfTicketsEntry"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(103, 103, 103))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adultTicketType)
                    .addComponent(jLabel3)
                    .addComponent(studentTicketType)
                    .addComponent(seniorTicketType)
                    .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(musicalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(timeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(80, 80, 80)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(numberOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dayOfMusicals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 15, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printButton)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adultTicketType)
                    .addComponent(musicalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayOfMusicals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentTicketType)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seniorTicketType)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookButton)
                    .addComponent(printButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        musicalTextArea.setColumns(20);
        musicalTextArea.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        musicalTextArea.setRows(5);
        musicalTextArea.setName("musicalsTextArea"); // NOI18N
        jScrollPane1.setViewportView(musicalTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musicalListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicalListButtonActionPerformed
        // TODO add your handling code here:
//        Musical musical = new Musical();
//        Musical musical2 = new Musical();
//        Musical musical3 = new Musical();
//        Musical musical4 = new Musical();
//        Musical musical5 = new Musical();
//        Musical musical6 = new Musical();
//
//
//        
////        List<Musical> musicals = new List<Musical>;
//        
//                //instantiating musicals
//        musical.setMusicalName("Mamma Mia");
//        musical.setHeirarchy("1");
//        musical.setCategories("Animation, Cool");
//        musical.setVenue("Lyceum Theatre");
//        musical.setAges("7+");
//        musical.setRunTime("2h:13m (incl. interval)");
//        
//        musical2.setMusicalName("The Lion King");
//        musical2.setHeirarchy("2");
//        musical2.setCategories("Animation, Adventure");
//        musical2.setVenue("Lyceum Theatre");
//        musical2.setAges("7+");
//        musical2.setRunTime("1h:43m (incl. interval)");
//        
//        musical3.setMusicalName("Frozen");
//        musical3.setHeirarchy("3");
//        musical3.setCategories("Animation, Adventure");
//        musical3.setVenue("Lyceum Theatre");
//        musical3.setAges("7+");
//        musical3.setRunTime("2h:04m (incl. interval)");
//        
//        musical4.setMusicalName("Wicked");
//        musical4.setHeirarchy("4");
//        musical4.setCategories("Animation, Cool");
//        musical4.setVenue("Lyceum Theatre");
//        musical4.setAges("7+");
//        musical4.setRunTime("2h:13m (incl. interval)");
//        
//        musical5.setMusicalName("Matilda");
//        musical5.setHeirarchy("5");
//        musical5.setCategories("Animation, Adventure");
//        musical5.setVenue("Lyceum Theatre");
//        musical5.setAges("7+");
//        musical5.setRunTime("1h:54m (incl. interval)");
//        
//        musical6.setMusicalName("Moana");
//        musical6.setHeirarchy("6");
//        musical6.setCategories("Animation, Adventure");
//        musical6.setVenue("Lyceum Theatre");
//        musical6.setAges("7+");
//        musical6.setRunTime("2h:30m (incl. interval)");
//        
//        //FILL THE TEXT AREA WITH THE MUSICAL DATA
//        musicalTextArea.setText(musical.getHeirarchy() + ". " + musical.getMusicalName() + "\nRun time: " + musical.getRunTime() + "\nCategories: " + musical.getCategories() + "\nVenue :" + musical.getVenue() + "\nAges: " + musical.getAges() + "\n\n"
//                + musical2.getHeirarchy() + ". " + musical2.getMusicalName() + "\nRun time: " + musical2.getRunTime() + "\nCategories: " + musical2.getCategories() + "\nVenue :" + musical2.getVenue() + "\nAges: " + musical2.getAges() + "\n\n"
//                + musical3.getHeirarchy() + ". " + musical3.getMusicalName() + "\nRun time: " + musical3.getRunTime() + "\nCategories: " + musical3.getCategories() + "\nVenue :" + musical3.getVenue() + "\nAges: " + musical3.getAges() + "\n\n"
//                + musical4.getHeirarchy() + ". " + musical4.getMusicalName() + "\nRun time: " + musical4.getRunTime() + "\nCategories: " + musical4.getCategories() + "\nVenue :" + musical4.getVenue() + "\nAges: " + musical4.getAges() + "\n\n"
//                + musical5.getHeirarchy() + ". " + musical5.getMusicalName() + "\nRun time: " + musical5.getRunTime() + "\nCategories: " + musical5.getCategories() + "\nVenue :" + musical5.getVenue() + "\nAges: " + musical5.getAges() + "\n\n"
//                + musical6.getHeirarchy() + ". " + musical6.getMusicalName() + "\nRun time: " + musical6.getRunTime() + "\nCategories: " + musical6.getCategories() + "\nVenue :" + musical6.getVenue() + "\nAges: " + musical6.getAges() + "\n\n");


        //READ FROM FILE
        //A class used to load the files into the JVM to be used at runtime
//        ClassLoader classLoader = getClass().getClassLoader();

        InputStream file = Booking.class.getResourceAsStream("Musicals.txt");
        
        
        
            
            try(BufferedReader reader = new BufferedReader(new InputStreamReader(file))){
            
                String line;
 
                while((line = reader.readLine()) != null){
                    //display it to the text area
                    musicalTextArea.append(line);
                }
            }
            catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error reading the file", "Error", JOptionPane.ERROR_MESSAGE);
            }
        

//        musicalTextArea.getText();

          
    }//GEN-LAST:event_musicalListButtonActionPerformed

    private void showSchedulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSchedulesButtonActionPerformed
        //Set the available dates, time slots, and seats of musicals
        musicalTextArea.setText("Monday \nTime slots: 11:am, 4:pm, 7:pm\nNumber of seats: 89\n\n" +
                "Teusday \nTime slots: 11:am, 4:pm, 7:pm\nNumber of seats: 93\n\n" +
                "Wednessday \nTime slots: 11:am, 4:pm, 7:pm\nNumber of seats: 65\n\n" +
                "Thursday \nTime slots: 11:am, 4:pm, 7:pm\nNumber of seats: 65\n\n" +
                "Friday \nTime slots: 11:am, 4:pm, 7:pm\nNumber of seats: 80\n\n" +
                "Saturday \nTime slots: 11:am, 4:pm, 7:pm\nNumber of seats: 150\n\n" +
                "Sunday \nTime slots: 11:am, 4:pm, 7:pm\nNumber of seats: 170\n\n");  
        
        //display the data on the Text Area 
        musicalTextArea.getText();
    }//GEN-LAST:event_showSchedulesButtonActionPerformed

    //The BOOK button method basically instantiates a Ticket object
    Ticket ticket = new Ticket();
    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
//        musicalTextArea.setText(musicalName.getSelectedItem().toString());
//        musicalTextArea.getText();

        try{
            Integer.valueOf(seatNumber.getText());
            Integer.valueOf(numberOfTickets.getText());

            JOptionPane.showMessageDialog(printButton, "TICKET BOOKED! YOU CAN NOW PRINT YOUR RECIEPT", "TICKET BOOKED", HEIGHT, UIManager.getIcon("OptionPane.informationIcon"));

        }
        catch(NumberFormatException exc){
            JOptionPane.showMessageDialog(printButton, "Seat Number and Number of Tickets must be valid integers!", "WRONG VALUE", HEIGHT);
        }
        



        //MUSICAL NAME..
        ticket.setMusicalName(musicalName.getSelectedItem().toString());
        
//        

        //TICKET TYPE AND PRICE..
        //if the user selects the a particular ticket type, add the price to the ticket.
        if(adultTicketType.isSelected()){
            //fill in the ticket type and price accordingly..
            ticket.setTicketType("Adult");
            
            ticket.setPrice(16);
        }
        else if(seniorTicketType.isSelected()){
            //fill in the ticket type and price accordingly..
            ticket.setTicketType("Senior");
            
            ticket.setPrice(10);
        }
        else if(studentTicketType.isSelected()){
            //fill in the ticket type and price accordingly..
            ticket.setTicketType("Student");
            
            ticket.setPrice(7);
        }
        
        //NUMBER OF TICKETS..
        if((adultTicketType.isSelected() && seniorTicketType.isSelected()) 
                || (adultTicketType.isSelected() && studentTicketType.isSelected() || 
                (seniorTicketType.isSelected() && studentTicketType.isSelected()))){
            
            numberOfTickets.setText("2");
            ticket.setNoOfTickets(2);

            
            ticket.setNoOfTickets(Integer.parseInt(numberOfTickets.getText()));
        }
        else if(adultTicketType.isSelected() && seniorTicketType.isSelected() && studentTicketType.isSelected()){
            
            numberOfTickets.setText("3");
            ticket.setNoOfTickets(3);
        }
        
        //DATE..
        ticket.setDay(dayOfMusicals.getSelectedItem().toString());
        
        //TIMESLOT
        ticket.setTimeSlot(timeSlot.getSelectedItem().toString());
        
        //SEAT NUMBER..
        ticket.setSeatNumber(Integer.parseInt(seatNumber.getText()));
        
    }//GEN-LAST:event_bookButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
        
        
        TicketingSystem ticketSys = new TicketingSystem();
        

        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adultTicketType;
    private javax.swing.JButton bookButton;
    private javax.swing.JComboBox<String> dayOfMusicals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton musicalListButton;
    private javax.swing.JComboBox<String> musicalName;
    public javax.swing.JTextArea musicalTextArea;
    private javax.swing.JTextField numberOfTickets;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField seatNumber;
    private javax.swing.JRadioButton seniorTicketType;
    private javax.swing.JButton showSchedulesButton;
    private javax.swing.JRadioButton studentTicketType;
    private javax.swing.JComboBox<String> timeSlot;
    // End of variables declaration//GEN-END:variables
}
